name: Cypress Tests for Test Branch

on:
  push:
    branches:
      - test # Executa apenas na branch 'test'
  pull_request:
    branches:
      - test # Executa quando houver PRs na branch 'test'
  workflow_dispatch: # Permite execução manual

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cypress:run -- --spec "cypress/integration/**/**/*.spec.js"
        env:
          CI: true
