name: End-to-end tests
on:
  # Executar automaticamente em push para test e master
  push:
    branches:
      - test
      - master

  # Permitir execução manual
  workflow_dispatch:
    inputs:
      folder:
        description: "cypress/integration/shared"
        required: true
        default: shared
        type: choice
        options:
          - shared
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
